//! Gateway handlers module
//!
//! This module contains all HTTP handlers organized by domain.

pub mod account;
pub mod exchange;
pub mod health;
pub mod helpers;
pub mod jwt;
pub mod market;
pub mod order;
pub mod query;
pub mod transfer;

// Re-export all public handlers for backward compatibility
pub use account::{get_account, get_all_balances, get_balances};
pub use exchange::{AssetApiData, ExchangeInfoData, SymbolApiData};
pub use exchange::{get_assets, get_exchange_info, get_symbols};
pub use health::{HealthResponse, health_check};
pub use helpers::{DepthFormatter, now_ms, now_ns};
pub use jwt::{
    cancel_order_jwt, create_order_jwt, create_transfer_jwt, get_account_jwt, get_balance_jwt,
    get_orders_jwt,
};
pub use market::{get_depth, get_klines};
pub use order::{cancel_order, cancel_order_by_id, create_order, move_order, reduce_order};
pub use query::{get_order, get_orders, get_public_trades, get_trades};
pub use transfer::{create_transfer, get_transfer};

// Re-export utoipa path types for OpenAPI doc generation
// These are generated by #[utoipa::path] attribute macros
pub use account::__path_get_account;
pub use account::__path_get_all_balances;
pub use account::__path_get_balances;
pub use exchange::__path_get_assets;
pub use exchange::__path_get_exchange_info;
pub use exchange::__path_get_symbols;
pub use health::__path_health_check;
pub use market::__path_get_depth;
pub use market::__path_get_klines;
pub use order::__path_cancel_order;
pub use order::__path_create_order;
pub use order::__path_move_order;
pub use order::__path_reduce_order;
pub use query::__path_get_order;
pub use query::__path_get_orders;
pub use query::__path_get_public_trades;
pub use query::__path_get_trades;
pub use transfer::__path_create_transfer;
pub use transfer::__path_get_transfer;
