//! WebSocket message types
//!
//! Defines the message formats for WebSocket communication between
//! server and clients, following API conventions.

use crate::models::{OrderStatus, Side};
use serde::{Deserialize, Serialize};

/// WebSocket message sent to clients
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum WsMessage {
    /// Connection established
    Connected { user_id: u64 },
    /// Order status update
    OrderUpdate {
        order_id: u64,
        symbol: String,
        status: String, // SCREAMING_CASE: "NEW", "FILLED", etc.
        filled_qty: String,
        avg_price: Option<String>,
    },
    /// Trade notification
    Trade {
        trade_id: u64,
        order_id: u64,
        symbol: String,
        side: String, // "BUY" or "SELL"
        price: String,
        qty: String,
        role: String, // "MAKER" or "TAKER"
    },
    /// Balance update
    BalanceUpdate {
        asset: String,
        avail: String,
        frozen: String,
    },
    /// Pong response to ping
    Pong,
}

/// Push event (internal queue message)
///
/// These events are generated by Settlement service and consumed
/// by WsService to send WebSocket messages to clients.
#[derive(Debug, Clone)]
pub enum PushEvent {
    /// Order status changed
    OrderUpdate {
        user_id: u64,
        order_id: u64,
        symbol_id: u32,
        status: OrderStatus,
        filled_qty: u64,
        avg_price: Option<u64>,
    },
    /// Trade executed
    Trade {
        user_id: u64,
        trade_id: u64,
        order_id: u64,
        symbol_id: u32,
        side: Side,
        price: u64,
        qty: u64,
        role: u8, // 0=Maker, 1=Taker
    },
    /// Balance changed
    BalanceUpdate {
        user_id: u64,
        asset_id: u32,
        avail: u64,
        frozen: u64,
    },
}
